
    create table tb_department (
       id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table tb_packaging (
       barCode varchar(255),
        conversionFactor double,
        description varchar(255),
        grossWeight double,
        netWeight double,
        unity_id varchar(255) not null,
        product_id bigint not null,
        primary key (product_id, unity_id)
    );

    create table tb_product (
       id bigint not null,
        averageCost double,
        barCode varchar(255),
        code varchar(255),
        commission double,
        description varchar(255),
        grossWeight double,
        lastEntryCost double,
        maxMargin double,
        minMargin double,
        minPrice double,
        netWeight double,
        outLine boolean,
        salePrice double,
        stockBalance double,
        department_id bigint,
        section_id bigint,
        unity_id varchar(255),
        primary key (id)
    );

    create table tb_role (
       id bigint generated by default as identity,
        authority varchar(255),
        description varchar(255),
        primary key (id)
    );

    create table tb_section (
       id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table tb_unity (
       id varchar(255) not null,
        description varchar(255),
        primary key (id)
    );

    create table tb_user (
       id bigint generated by default as identity,
        login varchar(255),
        name varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table tb_user_role (
       user_id bigint not null,
        role_id bigint not null,
        primary key (user_id, role_id)
    );

    alter table tb_user 
       add constraint UK_qht682qvopcx5f41dc2rbs5jf unique (login);

    alter table tb_packaging 
       add constraint FK14n2rr8rsxpanlgebbxq8t7r7 
       foreign key (unity_id) 
       references tb_unity;

    alter table tb_packaging 
       add constraint FK4w6rojt5cqnfjk6otxidg19m3 
       foreign key (product_id) 
       references tb_product;

    alter table tb_product 
       add constraint FKi5b17771bifanjax4awtcu63i 
       foreign key (department_id) 
       references tb_department;

    alter table tb_product 
       add constraint FKh29i9kke6o4xvvacoib20i0qi 
       foreign key (section_id) 
       references tb_section;

    alter table tb_product 
       add constraint FKrcg0qwq5yq9um1x84h8u957m 
       foreign key (unity_id) 
       references tb_unity;

    alter table tb_user_role 
       add constraint FKea2ootw6b6bb0xt3ptl28bymv 
       foreign key (role_id) 
       references tb_role;

    alter table tb_user_role 
       add constraint FK7vn3h53d0tqdimm8cp45gc0kl 
       foreign key (user_id) 
       references tb_user;

    create table tb_accounts_receivable (
       document bigint not null,
        parcel varchar(255) not null,
        dueDate date,
        issueDate date,
        value double,
        client_id bigint,
        formPayment_id varchar(255),
        paymentPlan_id bigint,
        seller_id bigint,
        primary key (document, parcel)
    );

    create table tb_city (
       id bigint not null,
        name varchar(255),
        state varchar(255),
        primary key (id)
    );

    create table tb_client (
       id bigint not null,
        cep varchar(255),
        clientType integer,
        cpfCnpj varchar(255),
        creditLimit double,
        deliveryNote varchar(255),
        district varchar(255),
        email varchar(255),
        enable boolean not null,
        fantasyName varchar(255),
        fixedPhone varchar(255),
        generalNote varchar(255),
        lastBuy date,
        mobilePhone varchar(255),
        name varchar(255),
        number varchar(255),
        specialPrice boolean not null,
        street varchar(255),
        validateFinancialBlock boolean not null,
        city_id bigint,
        formPayment_id varchar(255),
        lineBusiness_id bigint,
        paymentPlan_id bigint,
        seller_id bigint,
        square_id bigint,
        primary key (id)
    );

    create table tb_department (
       id bigint not null,
        name varchar(255),
        primary key (id)
    );

    create table tb_form_payment (
       id varchar(255) not null,
        name varchar(255),
        primary key (id)
    );

    create table tb_line_business (
       id bigint not null,
        name varchar(255),
        primary key (id)
    );

    create table tb_packaging (
       barCode varchar(255),
        conversionFactor double,
        description varchar(255),
        grossWeight double,
        netWeight double,
        unity_id varchar(255) not null,
        product_id bigint not null,
        primary key (product_id, unity_id)
    );

    create table tb_payment_plan (
       id bigint not null,
        averageTime integer,
        financialRate double,
        firstInterval integer,
        name varchar(255),
        parcelsInterval integer,
        parcelsNumber integer,
        primary key (id)
    );

    create table tb_product (
       id bigint not null,
        averageCost double,
        barCode varchar(255),
        code varchar(255),
        commission double,
        description varchar(255),
        enable boolean not null,
        grossWeight double,
        lastEntryCost double,
        maxMargin double,
        minMargin double,
        minPrice double,
        netWeight double,
        salePrice double,
        stockBalance double,
        department_id bigint,
        section_id bigint,
        unity_id varchar(255),
        primary key (id)
    );

    create table tb_role (
       id bigint generated by default as identity,
        authority varchar(255),
        description varchar(255),
        primary key (id)
    );

    create table tb_section (
       id bigint not null,
        name varchar(255),
        primary key (id)
    );

    create table tb_seller (
       id bigint not null,
        commission double,
        enable boolean not null,
        lastConection timestamp,
        name varchar(255),
        primary key (id)
    );

    create table tb_square (
       id bigint not null,
        name varchar(255),
        primary key (id)
    );

    create table tb_unity (
       id varchar(255) not null,
        description varchar(255),
        primary key (id)
    );

    create table tb_user (
       id bigint generated by default as identity,
        login varchar(255),
        name varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table tb_user_role (
       user_id bigint not null,
        role_id bigint not null,
        primary key (user_id, role_id)
    );

    alter table tb_user 
       add constraint UK_qht682qvopcx5f41dc2rbs5jf unique (login);

    alter table tb_accounts_receivable 
       add constraint FKo82otpmq6f56m1yfv8cfh54no 
       foreign key (client_id) 
       references tb_client;

    alter table tb_accounts_receivable 
       add constraint FKujaoi5veegl15ugyey8fycj3 
       foreign key (formPayment_id) 
       references tb_form_payment;

    alter table tb_accounts_receivable 
       add constraint FKkvqti2tb5oiqfnos9x66dj942 
       foreign key (paymentPlan_id) 
       references tb_payment_plan;

    alter table tb_accounts_receivable 
       add constraint FKtqwhyugem41k39gc981gqxy1o 
       foreign key (seller_id) 
       references tb_seller;

    alter table tb_client 
       add constraint FK26iqvaig0po6a1m4sq5gc1g41 
       foreign key (city_id) 
       references tb_city;

    alter table tb_client 
       add constraint FKa9h4ewkrj5r7maoy8wasjqb0w 
       foreign key (formPayment_id) 
       references tb_form_payment;

    alter table tb_client 
       add constraint FKabeu32nv7cokkmerwgmwej6qv 
       foreign key (lineBusiness_id) 
       references tb_line_business;

    alter table tb_client 
       add constraint FKqi4ey9tm39u636br718c5l33y 
       foreign key (paymentPlan_id) 
       references tb_payment_plan;

    alter table tb_client 
       add constraint FKnyl35vff1s0rmjd7647tlx29c 
       foreign key (seller_id) 
       references tb_seller;

    alter table tb_client 
       add constraint FKbmgh093ln8ftb6844ihlar3fv 
       foreign key (square_id) 
       references tb_square;

    alter table tb_packaging 
       add constraint FK14n2rr8rsxpanlgebbxq8t7r7 
       foreign key (unity_id) 
       references tb_unity;

    alter table tb_packaging 
       add constraint FK4w6rojt5cqnfjk6otxidg19m3 
       foreign key (product_id) 
       references tb_product;

    alter table tb_product 
       add constraint FKi5b17771bifanjax4awtcu63i 
       foreign key (department_id) 
       references tb_department;

    alter table tb_product 
       add constraint FKh29i9kke6o4xvvacoib20i0qi 
       foreign key (section_id) 
       references tb_section;

    alter table tb_product 
       add constraint FKrcg0qwq5yq9um1x84h8u957m 
       foreign key (unity_id) 
       references tb_unity;

    alter table tb_user_role 
       add constraint FKea2ootw6b6bb0xt3ptl28bymv 
       foreign key (role_id) 
       references tb_role;

    alter table tb_user_role 
       add constraint FK7vn3h53d0tqdimm8cp45gc0kl 
       foreign key (user_id) 
       references tb_user;
