
    create table tb_department (
       id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table tb_packaging (
       barCode varchar(255),
        conversionFactor double,
        description varchar(255),
        grossWeight double,
        netWeight double,
        unity_id varchar(255) not null,
        product_id bigint not null,
        primary key (product_id, unity_id)
    );

    create table tb_product (
       id bigint not null,
        averageCost double,
        barCode varchar(255),
        code varchar(255),
        commission double,
        description varchar(255),
        grossWeight double,
        lastEntryCost double,
        maxMargin double,
        minMargin double,
        minPrice double,
        netWeight double,
        outLine boolean,
        salePrice double,
        stockBalance double,
        department_id bigint,
        section_id bigint,
        unity_id varchar(255),
        primary key (id)
    );

    create table tb_role (
       id bigint generated by default as identity,
        authority varchar(255),
        description varchar(255),
        primary key (id)
    );

    create table tb_section (
       id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
    );

    create table tb_unity (
       id varchar(255) not null,
        description varchar(255),
        primary key (id)
    );

    create table tb_user (
       id bigint generated by default as identity,
        login varchar(255),
        name varchar(255),
        password varchar(255),
        primary key (id)
    );

    create table tb_user_role (
       user_id bigint not null,
        role_id bigint not null,
        primary key (user_id, role_id)
    );

    alter table tb_user 
       add constraint UK_qht682qvopcx5f41dc2rbs5jf unique (login);

    alter table tb_packaging 
       add constraint FK14n2rr8rsxpanlgebbxq8t7r7 
       foreign key (unity_id) 
       references tb_unity;

    alter table tb_packaging 
       add constraint FK4w6rojt5cqnfjk6otxidg19m3 
       foreign key (product_id) 
       references tb_product;

    alter table tb_product 
       add constraint FKi5b17771bifanjax4awtcu63i 
       foreign key (department_id) 
       references tb_department;

    alter table tb_product 
       add constraint FKh29i9kke6o4xvvacoib20i0qi 
       foreign key (section_id) 
       references tb_section;

    alter table tb_product 
       add constraint FKrcg0qwq5yq9um1x84h8u957m 
       foreign key (unity_id) 
       references tb_unity;

    alter table tb_user_role 
       add constraint FKea2ootw6b6bb0xt3ptl28bymv 
       foreign key (role_id) 
       references tb_role;

    alter table tb_user_role 
       add constraint FK7vn3h53d0tqdimm8cp45gc0kl 
       foreign key (user_id) 
       references tb_user;
